import Home from "views/home";
import Error404 from "./components/blocked/Error404";

const MainPagesList = [
  {
    title: "Home",
    path: "home",
    icon: "home",
    layout: "admin",
    component: Home,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
    show: false,
  },
  {
    title: "Work Routes",
    path: "",
    icon: "map",
    layout: "admin",
    component: Error404,
    show: true,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
  },
  {
    title: "Review",
    path: "routes/review",
    icon: null,
    layout: "admin",
    component: Error404,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
  },
  {
    title: "Routes Manager",
    path: "routes/manage",
    icon: "null",
    layout: "admin",
    component: Error404,
    allowedRoles: ["Root", "Administrator"],
  },
  {
    title: "Pacients",
    path: "",
    icon: "local_hospital",
    layout: "admin",
    component: Error404,
    show: true,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
  },
  {
    title: "Review",
    path: "pacients/review",
    icon: null,
    layout: "admin",
    component: Error404,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
  },
  {
    title: "Pacients Manager",
    path: "pacients/manage",
    icon: "null",
    layout: "admin",
    component: Error404,
    allowedRoles: ["Root", "Administrator", "Local Member"],
  },
  {
    title: "Clinics",
    path: "",
    icon: "location_city",
    layout: "admin",
    component: Error404,
    show: true,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
  },
  {
    title: "Review",
    path: "clinics/review",
    icon: null,
    layout: "admin",
    component: Error404,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
  },
  {
    title: "Clinics Manager",
    path: "clinics/manage",
    icon: "null",
    layout: "admin",
    component: Error404,
    allowedRoles: ["Root", "Administrator"],
  },
  {
    title: "Calendar",
    path: "routes/calendar",
    icon: "calendar_today",
    layout: "admin",
    component: Error404,
    children: null,
    show: true,
    allowedRoles: [
      "Root",
      "Administrator",
      "Local Member",
      "Support Doctor",
      "Sponsor",
    ],
  },
  {
    title: "Management",
    path: "management/noseque",
    icon: "settings_applications",
    layout: "admin",
    component: Error404,
    children: null,
    show: true,
    allowedRoles: ["Root"],
  },
  {
    title: "Create User",
    path: "create-user",
    icon: "settings_applications",
    layout: "admin",
    component: Error404,
    children: null,
    show: true,
    allowedRoles: ["Root"],
  },
];

export default MainPagesList;
